apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: idp
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    managed-by: idp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: dev
        managed-by: idp
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}