apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: idp
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    managed-by: idp
    source: {{ .Values.source }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: {{ .Values.env }}
        managed-by: idp
        source: {{ .Values.source }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}