{{- if ne .Values.type "worker" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: idp
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    managed-by: idp
    source: {{ .Values.source }}
spec:
  selector:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    managed-by: idp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ if eq .Values.type "web" }}NodePort{{ else }}ClusterIP{{ end }}
{{- end }}